# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yen-wen Chin
title: Data Science graduate Student at University of Michigan
subtitle: Go Blue! Go Maize! ğŸ’™ğŸ’›
email: yenwenchin2025@gmail.com
website: https://www.linkedin.com/in/yenwen-chin/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: yenwen-chin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_1.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Yen-wen Chin â€” currently wrapping up my Masterâ€™s degree in Data Science, graduating in May 2025. I love using data and technology to solve real-world problems, especially when it means making systems more efficient and information more accessible.

  Iâ€™m originally from Taiwan, and part of the reason I came to the U.S. was to explore different ways of living and learning. Iâ€™ve always been curious â€” not just about how things work, but how people work together, and how technology can help us do that better.

  Over the past few years, Iâ€™ve built full-stack applications, automated data pipelines, created Power BI dashboards for scientists and engineers, and integrated GPT-powered features into mobile apps. I enjoy working across disciplines, and I thrive when Iâ€™m learning something new.

  Iâ€™m currently studying for the AWS Solutions Architect Associate certification to strengthen my cloud skills, and Iâ€™m open to opportunities across the U.S. Iâ€™m happy to relocate â€” and I do not require sponsorship for the next 3 years.

  Tools I love working with: <mark>Python</mark>, <mark>Powershell</mark>, <mark>Linux</mark>, <mark>SQL</mark>, <mark>Splunk</mark>, and <mark>Power BI</mark>.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ğŸ”§ Automated Alert Workflow with Splunk and ESB Integration
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
          # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          - Python (CSV parsing, file handling, API calls)  
          - Shell Script (automation and scheduling)  
          - Splunk (data source)  
          - ESB integration (via custom file-based messaging)  
          - Linux cron jobs (for scheduled execution)  
        description: | # this will include new lines to allow paragraphs
          This diagram illustrates the automated alert processing pipeline I developed during my previous role. 
          The system retrieves scheduled reports from Splunk, processes and enriches the data, 
          and sends the output to an external ESB (Enterprise Service Bus) system for downstream consumption.
          ![splunk_workflow](/images/Splunk_ESB.png "splunk_workflow")

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Michigna Medicine
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: API Data Engineer
        caption: Sep 2024 â€“ Feb 2025
        quote: >
          Developed a full-stack application that integrated a React Native chat interface with a PHP backend and MySQL database, enabling real-time communication with UMGPT.
        skills: | # this will include new lines to allow paragraphs
          <mark>React Native</mark>, <mark>PHP</mark>, <mark>MySQL</mark>, <mark>Docker</mark>, <mark>Knex</mark>, <mark>Postman</mark>
        description: | # this will include new lines to allow paragraphs
          - Developed RESTful APIs using PHP and MySQL to power GPT-integrated chat functionality in a mobile application,
          enabling real-time, intelligent conversations
          - Designed and implemented a secure database schema and executed SQL migrations using Knex.js, ensuring data
          consistency and supporting new feature rollouts
          - Maintained a Docker-based local development environment to support backend integration
          - Validated API functionality using Postman and TablePlus to ensure accurate requestâ€“response behavior
          - Collaborated with non-technical stakeholders to define API requirements and translated technical specifications into user-
          centric deliverables and progress reports
      - layout: left
        title: Boehringer Ingelheim
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Data Analyst Intern
        caption: May 2024 â€“ August 2024
        quote: >
          Built automated workflows that made complex reporting simple â€” so that leaders could focus on decisions, not data cleanup.
        skills: | # this will include new lines to allow paragraphs
          <mark>Power BI</mark>, <mark>Shell Script</mark>, <mark>SharePoint</mark>, <mark>Agile</mark>
        description: | # this will include new lines to allow paragraphs
          - Developed an automated data extraction solution from SFTP to CSV using Shell Script and Task Scheduler, reducing
          manual data retrieval time by 60%
          - Built a Power BI dashboard that visualized data quality and governance metrics from SharePoint, enabling real-time
          visibility for strategic decision-making
          - Worked closely with scientists to identify key metrics and co-develop Power BI dashboards, enhancing cross-team data
          accessibility and standardizing reporting workflows under agile methodology
          - Authored clear, process-oriented documentation to support knowledge transfer and reduce onboarding time
      - layout: left
        title: Systex Co., Ltd
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Systems Engineer
        caption: May 2022 â€“ May 2023
        quote: >
          Automated data pipelines, streamlined system upgrades, and built real-time dashboards to turn complex data into actionable insights
        skills: | # this will include new lines to allow paragraphs
          <mark>Data Pipeline Automation</mark> Â· <mark>ETL Process</mark> Â· <mark>Splunk Dashboards</mark> Â· <mark>SQL Query Optimization</mark> Â· <mark>System Integration</mark> Â· <mark>Alert System via API</mark>
        description: | # this will include new lines to allow paragraphs
          - Designed and automated ETL pipelines to ingest and structure raw files and spreadsheets into databases, reducing manual
          data preparation time by 40% and improving reporting accuracy
          - Integrated Splunk with IBM TSM and NFS systems for real-time monitoring and alerting, cutting manual tracking
          workload by 50% and improving system resource utilization by 15%
          - Led a Proof of Concept (PoC) integrating Splunk with an ESB system, automating alert workflows via Python and Linux
          crontab scheduling, decreasing incident response time by 25% and saving 6+ hours/week of manual effort
          - Used VMware to simulate and test upgrade scenarios across development, test, and production environments, reducing
          deployment risk and shortening upgrade timelines
          - Collaborated to draft User Acceptance Testing (UAT) documentation for a client project, gaining hands-on experience in
          system validation and business requirement alignment
   
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Michigan â€“ Ann Arbor
        caption: Sep 2023 â€“ Present
        sub_title: Master of Science in Data Science
        quote: >
          Discovered a new passion for Michigan football ğŸˆ and the electrifying game-day energy â€” forever a Wolverine fan! ğŸ’™ğŸ’›
        description: | # this will include new lines to allow paragraphs
          - Currently pursuing a Master of Science in Data Science at the University of Michigan, with an expected graduation date of May 2025.
          - Coursework includes advanced topics in data science, machine learning, and data visualization.

      - layout: left
        title: National Sun Yat-sen University
        caption: Sep 2017 â€“ Jun 2021
        sub_title: Bachelor of Information System Management
        description: | 
          ğŸ³ï¸â€ğŸŒˆ Reconnected with my identity and advocated for LGBTQ+ and womenâ€™s rights 

          ğŸ“£ Participated in civic movements, including street campaigns and voter mobilization 

          ğŸ’¡ College was a turning point for personal growth and social engagement 

         
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
